### ISSUE TITLE
Como trocar a cor?

### ISSUE THREAD

**Issue by agentelinux** [bgsouza/meu-primeiro-app#1]
Eu preciso trocar a cor de fundo para um projeto.

**Comment by bgsouza** [comment]
Não temos essa funcionalidade disponível ainda. ='(

**Comment by NaraGuimma** [comment]
tem previsão para isso?

**Comment by thalisses** [comment]
Algum #frontender online?

**Comment by bgsouza** [comment]
Ainda não...mas talvez na v2
